### ISSUE TITLE
Tracking issue - pull in changes from upstream

### ISSUE THREAD

**Issue by bhousel** [facebookincubator/RapiD#202]
This is just a placeholder issue for the work I'm pulling in from the upstream iD repo.  
We're caught up to `develop` head and will include these Pull Requests in the next RapiD release.

- [x] Use Mapillary Vector Tile API (https://github.com/openstreetmap/iD/pull/8372)
- [x] Name Suggestion Index v5 (https://github.com/openstreetmap/iD/pull/8305)
- [x] Fix centroid calculation in measurement panel (https://github.com/openstreetmap/iD/pull/8341)
- [x] Allow validation severity to be overridden with url params (https://github.com/openstreetmap/iD/pull/8243)
- [x] Update all dependencies (numerous here, but it includes refreshes to things like osm-community-index, temaki, rollup)
