### ISSUE TITLE
Tracking issue - pull in changes from upstream for v1.1.6

### ISSUE THREAD

**Issue by bhousel** [facebookincubator/RapiD#280]
This is just a placeholder issue for the work I'm pulling in from the upstream iD repo.
We're caught up to `develop` branch head and will include these fixes in the next RapiD release.

- [x] https://github.com/openstreetmap/iD/pull/8523
- [x] https://github.com/openstreetmap/iD/pull/8577
- [x] https://github.com/openstreetmap/iD/pull/8618
- [x] https://github.com/openstreetmap/iD/pull/8625
- [x] https://github.com/openstreetmap/iD/pull/8626
- [x] https://github.com/openstreetmap/iD/pull/8627
- [x] https://github.com/openstreetmap/iD/pull/8628
- [x] https://github.com/openstreetmap/iD/pull/8637
- [x] https://github.com/openstreetmap/iD/pull/8638
- [x] https://github.com/openstreetmap/iD/pull/8642

**Comment by bhousel** [comment]
released today 🎉 
https://twitter.com/bhousel/status/1428384950110273543
