### ISSUE TITLE
Tracking issue - pull in changes from upstream for v1.1.9

### ISSUE THREAD

**Issue by bhousel** [facebookincubator/RapiD#470]
This is just a placeholder issue for the work I'm pulling in from elsewhere.
We will include these fixes in the next RapiD release.

- [x] https://github.com/openstreetmap/iD/pull/9089
- [x] https://github.com/openstreetmap/iD/pull/8881
- [x] https://github.com/openstreetmap/iD/pull/8975
- [x] https://github.com/openstreetmap/iD/pull/8988
- [x] https://github.com/openstreetmap/iD/pull/9019
- [x] https://github.com/openstreetmap/iD/pull/9074
- [x] https://github.com/openstreetmap/iD/pull/9080
- [x] https://github.com/openstreetmap/iD/pull/9021
